### ISSUE TITLE
Icons and label doesn't show when you define models.Manager()

### ISSUE THREAD

**Issue by hbkfabio** [lincolnloop/django-salmonella#28]
if you define:

```
class algo_manager_(models.Manager):
    def get_query_set(self):
        return super(algo_manager, self).get_query_set().filter(active=True)

class algo(models.Model):

    active=models.Booleand()
    ...
    ...
    test=algo_manager()
```

after you can define the salmonella_field in admin.py. You can't  see the add icon and remove icon. Too if you select a item from a choose popup the label doesn't return.

see the image.

![screenshot from 2013-12-18 15 05 30](https://f.cloud.github.com/assets/775684/1775958/3405ff56-680f-11e3-9f50-6869db01e423.png)

**Comment by bartTC** [comment]
@hbkfabio I'm not able to replicate your issue and don't fully understand the problem (specifically what does `test=algo_manager()` do here. Lots of things have changed since then, please reopen the issue if the problem persists.
