### ISSUE TITLE
widget not working with django 1.11

### ISSUE THREAD

**Issue by vinodpandey** [lincolnloop/django-salmonella#36]
Widget not working because of template based rendering in django 1.11
https://docs.djangoproject.com/en/1.11/releases/1.11/#template-widget-incompatibilities-1-11

**Comment by farridav** [comment]
*bump, I'm thinking about using this, and I'm on 1.11..

**Comment by ahankinson** [comment]
Specifically, it's not working because the magnifying-glass widget is now included by default in the raw id widget, and the Salmonella JS looks for specific information on its own magnifying-glass widget. 

The fix will be to figure out how to override the raw ID field widget and not show it.

**Comment by bartTC** [comment]
Fixed in version 1.1. 

https://pypi.python.org/pypi/django-salmonella/1.1

**Comment by ahankinson** [comment]
Thank you!

**Comment by vinodpandey** [comment]
Thank you so much!!
